In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
fake_df = pd.read_csv("../dataset/Fake.csv")
true_df = pd.read_csv("../dataset/True.csv")

In [7]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [9]:
fake_df.shape
true_df.shape

(21417, 4)

In [10]:
true_df.shape

(21417, 4)

In [11]:
fake_df.shape

(23481, 4)

In [12]:
fake_df.columns

Index(['title', 'text', 'subject', 'date'], dtype='object')

In [13]:
fake_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [14]:
true_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [15]:
fake_df["label"] = 0
true_df["label"] = 1

In [16]:
fake_df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [17]:
data = pd.concat([fake_df, true_df])

In [18]:
data.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [19]:
data = data.sample(frac=1)
data.reset_index(inplace=True)
data.drop(["index"], axis=1, inplace=True)

In [20]:
data["content"] = data["title"] + " " + data["text"]

In [21]:
data = data[["content","label"]]

In [22]:
data.head()

                                             content  label
0   Seth MacFarlane Responds To Orlando Shooting,...      0
1  WHOA! MAXINE WATERS Has Brain Freeze Mid-Inter...      0
2   Texas Teen Fatally Shoots Himself 5 Days Afte...      0
3  UK parliament expected to vote on Brexit deal ...      1
4   Oath Keeper Leader: If You ‘Waco’ The Bundy M...      0

In [23]:
import re
import string

In [24]:
def clean_text(text):

    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)

    return text

<>:4: SyntaxWarning: "\[" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\["? A raw string is also an option.
<>:6: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:10: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:4: SyntaxWarning: "\[" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\["? A raw string is also an option.
<>:6: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:10: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\VAISHNAVI\AppData\Local\Temp\ipykernel_2056\2326627570.py:4: SyntaxWarning: "\[" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\["? A raw string is also an option.
  text = re.sub('\[.*?\]', '', text)
C:\Users\VAISHNAVI\AppData\Local\Temp\ipykernel_2056\2326627570.py:6: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  text = re.sub('https?://\S+|www\.\S+', '', text)
C:\Users\VAISHNAVI\AppData\Local\Temp\ipykernel_2056\2326627570.py:10: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  text = re.sub('\w*\d\w*', '', text)

In [25]:
data["content"] = data["content"].apply(clean_text)

In [26]:
data.head()

                                             content  label
0   seth macfarlane responds to orlando shooting ...      0
1  whoa  maxine waters has brain freeze mid inter...      0
2   texas teen fatally shoots himself  days after...      0
3  uk parliament expected to vote on brexit deal ...      1
4   oath keeper leader  if you  waco  the bundy m...      0

In [27]:
from sklearn.model_selection import train_test_split

X = data["content"]
y = data["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

Xv_train = vectorizer.fit_transform(X_train)
Xv_test = vectorizer.transform(X_test)

In [29]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(Xv_train, y_train)

LogisticRegression()

In [30]:
from sklearn.metrics import accuracy_score

pred = model.predict(Xv_test)

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

Accuracy: 0.9869042316258352

In [31]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

[[5718   81]
 [  66 5360]]

In [32]:
def predict_news(news):

    news = clean_text(news)
    vector = vectorizer.transform([news])

    prediction = model.predict(vector)

    if prediction == 0:
        return "Fake News"
    else:
        return "True News"

In [33]:
predict_news("NASA confirms water found on Mars")

'Fake News'

In [34]:
import pickle

In [36]:
import os
import pickle

os.makedirs("../models", exist_ok=True)

pickle.dump(model, open("../models/fake_news_model.pkl", "wb"))
pickle.dump(vectorizer, open("../models/vectorizer.pkl", "wb"))

In [37]:
import pickle

pickle.dump(model, open("../models/fake_news_model.pkl", "wb"))

In [38]:
pickle.dump(vectorizer, open("../models/vectorizer.pkl", "wb"))